name: Push source
on:
  push:
    branches:
      - 'main'
    paths:
      - 'en-GB'
  workflow_dispatch:
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.repository == 'just-a-paw/language'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: npm ci
      - run: npm test
      - run: npm run crowdin-push
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN_PUSH }}
